export {default as Navbar} from './Navbar'
export {default as HeroSection} from './HeroSection'
export {default as AboutUs} from './AboutUs'
export {default as Projects} from './Projects'
export {default as Footer} from './Footer'
export {default as ServicesOffered} from './ServicesOffered'